### ISSUE TITLE
Fix XML Backup: Scribunto error

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/docker-backup#13]
**Describe the bug**
(A clear and concise description of what the bug is.)
- Backed up xml wikipages are not restorable because of encodign 
- see issue in backup-logs
- this occurs in production because of  some pages which are in production 
- in backup zip can be seen where the backup drops.
- locally  import mysql data from production then do backup and restore to reproduce the problem 

**Expected behavior**
(A clear and concise description of what you expected to happen.)
- restorable xml wikipages

**To Reproduce**

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
- In example, information about the device used for producing the bug

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

**Comment by dajuno** [comment]
some quick infos to trace the error...

error of in `restore.sh`:
![xml_error](https://user-images.githubusercontent.com/12959445/159729925-f05f92ff-1bee-4f68-bd27-5e24a467740a.png)

end of xml backup file to be restored:
![image](https://user-images.githubusercontent.com/12959445/159730251-972654b7-1421-4077-bbe0-6cfb9744404d.png)

errors in backup.sh:

![image](https://user-images.githubusercontent.com/12959445/160147700-578c6365-2b7b-490f-86d3-d7d5747c3e55.png)

**Comment by dajuno** [comment]
- this page causes the error: https://portal.mardi4nfdi.de/w/index.php?curid=25
- backup script claims Scribunto contenthandler is not installed. however, special:version lists the Scribunto extension
- no idea what encoding should have to do with that as alvaro claimed

TODO:
- check why scribunto content handler is not found
- ~~verify scribunto installation -> test case?~~

more notes:
- dumpBackup.php (same command as in backup.sh) works in mardi-wikibase container, but not in mardi-backup. something must be messed up with the shared config (permissions?)
- backups of scribunto content pages with lua code work locally (including identical code as the pages causing the errors)!
- deployed: also newly created pages in the Module: namespace with Lua code cause this error -> encoding error unlikely

-> problem occurs
- only on server, not locally
- only within mardi-backup, not mardi-wikibase
- with old and newly created pages within the Module namespace (Lua scripts)

**Comment by dajuno** [comment]
This is related to https://github.com/MaRDI4NFDI/portal-compose/pull/124 and refs therein and was actually already fixed as a collateral by https://github.com/MaRDI4NFDI/docker-wikibase/pull/13 (for jobrunner). The relative path in LocalSettings.php causes backup not to find LocalSettings.d/*.php. However, docker-wikibase will not create a new (fixed) LocalSettings.php if one exists already (creating new issue). The file has to be modified manually...

**Comment by dajuno** [comment]
modified `/shared/LocalSettings.php` directly to incorporate [PR#13](https://github.com/MaRDI4NFDI/docker-wikibase/pull/13/files#diff-86d9dba3e690f48fd1d9605a75e322a51121fe09a066f66d9aeb969920246e58)

issue of LocalSettings.php not being updated -> MaRDI4NFDI/docker-wikibase#21
